 --ZAD 1
 DESC EMP;
 DESC DEPT;
 DESC SALGRADE;
 DESC BONUS;
 DESC IMPLEMP;
 DESC PROJECT;
 DESC IMPLPROJECT;

-- ZAD 2
 SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO FROM EB.EMP;
 SELECT * FROM EMP;

-- ZAD 3
 SELECT DNAME FROM DEPT;

--ZAD 4
 SELECT DISTINCT JOB FROM EMP;

-- ZAD 5
 SELECT ENAME, EMPNO FROM EMP WHERE SAL >= 2500 AND SAL <= 3200;

--ZAD 6
 SELECT ENAME, HIREDATE FROM EMP WHERE JOB IN ('CLERK', 'MANAGER', 'SALESMAN');

-- ZAD 7
 SELECT SAL+NVL(COMM, 0), SAL, COMM FROM EMP WHERE COMM IS NOT NULL;

-- ZAD 8
 SELECT ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO IN (10, 20) ORDER BY ENAME ASC,  DEPTNO DESC;

-- ZAD 9
 SELECT ENAME, JOB, MGR FROM EMP WHERE MGR IS NULL;

-- ZAD 10
 SELECT ENAME, EMPNO, JOB, SAL FROM EMP WHERE JOB='CLERK' OR JOB='SALESMAN' AND SAL>1500;
 
 -- ZAD 11
SELECT ENAME AS NAZWISKO, DNAME AS NAZWA_DEPARTAMENTU, LOC
FROM EMP, DEPT
WHERE DEPT.deptno=EMP.deptno AND DEPT.loc!='CHICAGO';

-- ZAD 12
SELECT E1.ENAME 
FROM EMP E1, EMP E2 
WHERE E1.SAL > E2.SAL AND E2.DEPTNO=10;

-- ZAD 13
SELECT ENAME, SAL, SAL*1.25
FROM EMP 
WHERE SAL*1.25>3000;

-- ZAD 14
SELECT ENAME, TRUNC(MONTHS_BETWEEN(TO_DATE('2020-10-17', 'yyyy-mm-dd'), HIREDATE)), HIREDATE
FROM EMP;

-- ZAD 15
SELECT 'Pracownik o nazwisku ' || ENAME || ' nie posiada zwierzchnika'
FROM EMP
WHERE MGR IS NULL;

-- ZAD 16
SELECT LENGTH(ENAME), ENAME
FROM EMP;

-- ZAD 17
SELECT INITCAP(ENAME), LOWER(JOB)
FROM EMP;

-- ZAD 18
SELECT INITCAP(ENAME)
FROM EMP
WHERE SUBSTR(ENAME,1,2)='BL';

SELECT INITCAP(ENAME)
FROM EMP
WHERE INSTR(ENAME,'BL')=1;

SELECT INITCAP(ENAME)
FROM EMP
WHERE ENAME LIKE 'BL%';
