-- ZAD 1
-- DESC EMP;
-- DESC DEPT;
-- DESC SALGRADE;
-- DESC BONUS;
-- DESC IMPLEMP;
-- DESC PROJECT;
-- DESC IMPLPROJECT;

-- ZAD 2
-- SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO FROM EB.EMP;
-- SELECT * FROM EMP;

-- ZAD 3
-- SELECT DNAME FROM DEPT;

--ZAD 4
-- SELECT DISTINCT JOB FROM EMP;

-- ZAD 5
-- SELECT ENAME, EMPNO FROM EMP WHERE SAL >= 2500 AND SAL <= 3200;

--ZAD 6
-- SELECT ENAME, HIREDATE FROM EMP WHERE JOB IN ('CLERK', 'MANAGER', 'SALESMAN');

-- ZAD 7
-- SELECT SAL+NVL(COMM, 0), SAL, COMM FROM EMP WHERE COMM IS NOT NULL;

-- ZAD 8
-- SELECT ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO IN (10, 20) ORDER BY ENAME ASC,  DEPTNO DESC;

-- ZAD 9
-- SELECT ENAME, JOB, MGR FROM EMP WHERE MGR IS NULL;

-- ZAD 10
-- SELECT ENAME, EMPNO, JOB, SAL FROM EMP WHERE JOB='CLERK' OR JOB='SALESMAN' AND SAL>1500;
